import type { Metadata } from "next";
import localFont from "next/font/local";
import './global.css'
import { Body } from './layout.client'
import { RootProvider } from 'xyzdocs-radix-ui/provider/next'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <Body>
        <RootProvider theme={{ enabled: true }}>
          {/* <TreeContextProvider tree={source.getPageTree()}>
            <Provider> */}
          {children}
          {/* </Provider>
          </TreeContextProvider> */}
        </RootProvider>
      </Body>
    </html>
  )
}
